version: '2'
services:
  client1_12:
    user: "root:root"
    image: odoo:12.0
    depends_on:
      - db
    ports:
      - "8080:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
  db:
    image: postgres:10
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
      - client2_11-db-data-files:/var/lib/postgresql/data
volumes:
  odoo-web-data:
  odoo-db-data:
  client2_11-db-data-files:
