version: '2'
services:
  odoo:
    # build:
    #   context: .
    #   dockerfile: ./Dockerfile
    # image: mclfy82/odoo:11.0
    image: odoo:11.0
    depends_on:
      - db
    ports:
      - "8081:8069"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./custom-addons:/opt/odoo/odoo/custom-addons
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/
volumes:
  web-data:
  db-data:
  # custom-addons:

